# Generated by Django 4.2.5 on 2024-01-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rigistr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qavat', models.CharField(max_length=30)),
                ('raqam', models.PositiveIntegerField()),
                ('sigim', models.PositiveIntegerField(default=0)),
                ('tur', models.CharField(max_length=30)),
                ('narx', models.PositiveIntegerField()),
                ('bosh_joy_soni', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Joylashtirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(max_length=500)),
                ('kelgan_sana', models.DateField()),
                ('ketish_sana', models.DateField()),
                ('yotgan_kuni', models.DateField()),
                ('bosh_joy', models.IntegerField()),
                ('qarovchi', models.BooleanField(default=False)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigistr.bemor')),
                ('xona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xonalar.xona')),
            ],
        ),
    ]
