# Generated by Django 4.2.5 on 2024-01-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rigistr', '0001_initial'),
        ('xonalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField()),
                ('tolangan_summa', models.IntegerField()),
                ('tolandi', models.BooleanField()),
                ('created_sana', models.DateField()),
                ('tolangan_sana', models.DateField()),
                ('turi', models.CharField(max_length=20)),
                ('izoh', models.TextField(blank=True)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigistr.bemor')),
                ('joylashtirhs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xonalar.joylashtirish')),
                ('yollanma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rigistr.yollanma')),
            ],
        ),
    ]
